release: v1.0.19
Changelog:

- A1
- B2
- C3

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,106 +1,247 @@
-name: Linting & Tests Validation
+name: Desktop Release Build
+
+# Add environment variables at the top level
+env:
+  LINUX_ASSETS_URL: "https://github.com/pactus-project/pactus/releases/download/v1.6.4/pactus-cli_1.6.4_linux_amd64.tar.gz"
+  WINDOWS_AMD64_ASSETS_URL: "https://github.com/pactus-project/pactus/releases/download/v1.6.4/pactus-cli_1.6.4_windows_amd64.zip"
+  WINDOWS_386_ASSETS_URL: "https://github.com/pactus-project/pactus/releases/download/v1.6.4/pactus-cli_1.6.4_windows_386.zip"
+  MACOS_ARM64_ASSETS_URL: "https://github.com/pactus-project/pactus/releases/download/v1.6.4/pactus-cli_1.6.4_darwin_arm64.tar.gz"
+  MACOS_AMD64_ASSETS_URL: "https://github.com/pactus-project/pactus/releases/download/v1.6.4/pactus-cli_1.6.4_darwin_amd64.tar.gz"
+
+permissions:
+  contents: write
+  pull-requests: read
+
 on:
-  pull_request:
-    branches:
-      - develop
+  pull_request_target:
+    types: [closed]
+    branches: [ "main" ]
+
 jobs:
-  lint_and_test:
+
+  detect-release-commit:
+    if: github.event.pull_request.merged == true
     runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
+
+      - name: Extract PR Details
+        id: extract-pr
+        uses: ./.github/actions/extract-pr-details
+      - name: Print PR title and body
+        run: |
+          echo "PR Title: ${{ steps.extract-pr.outputs.pr_title }}"
+          echo "PR Body: ${{ steps.extract-pr.outputs.pr_body }}"
+
+  build-and-release-linux:
+    if: steps.extract-pr.outcome == 'success'
+    runs-on: ubuntu-latest
+    outputs:
+      release_tag: linux-release-number-${{ github.run_number }} # create tag/release
+      platform: Linux
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2
-      - name: Set up Flutter
+        uses: actions/checkout@v4
+
+      - name: Setup Flutter
         uses: subosito/flutter-action@v2
         with:
           flutter-version: '3.27.3'
-
-
-# Install dependencies
+          channel: 'stable'
+          cache: true
+      - name: Install Linux dependencies
+        uses: ./.github/actions/linux-install-dependencies
+      - name: Enable Linux desktop
+        run: flutter config --enable-linux-desktop
       - name: Install dependencies
         run: flutter pub get
-
-
-# Detect Dart Formatting Issues
-      - name: Run Dart Format Check (Efficient)
-        run: |
-          dart format . --set-exit-if-changed --output none || (
-            echo "Code formatting issues detected. Run 'dart format .' and commit the changes.";
-            exit 1;
-          )
-          
-# Generate Localization Files
       - name: Generate Localization Files
-        id: gen_l10n
-        run: |
-          # Run the command to generate localization files and capture the output
-          output=$(flutter gen-l10n)
-          echo "$output"
-
-          # Check if there are untranslated messages in the output
-          if echo "$output" | grep -q "untranslated message"; then
-            echo "::error file=lib/l10n/l10n.yaml::Error: Untranslated messages detected in your localization files."
-            echo "::error::There are untranslated messages in the following languages:"
-            echo "$output" | grep "untranslated message"
-            echo "::error::Please ensure that all translations are provided in the respective .arb files."
-            exit 1
-          fi
-
-# Detect Localization Files Changes
-      - name: Validate Generated Localization Files
-        run: |
-          # Check if localization files have changes
-          if git diff --exit-code lib/l10n/; then
-            echo "Localization files are up to date."
-          else
-            echo "::error file=lib/l10n/::Error: Localization files are outdated."
-            echo "::error::Please run 'flutter gen-l10n' and commit the changes."
-            exit 1
-          fi
-
-          # Check if translations_utils.dart has changes
-          if git diff --exit-code lib/src/core/utils/gen/localization/translations_utils.dart; then
-            echo "translations_utils.dart is up to date."
-          else
-            echo "::error file=lib/src/core/utils/gen/localization/translations_utils.dart::Error: Changes detected in translations_utils.dart."
-            echo "::error::Please run the necessary custom translation utilities and commit changes."
-            exit 1
-          fi
-
-
-
-# Generate Files Using build_runner
-      - name: Generate Files Using build_runner
-        run: |
-          # Run build_runner to generate files
-          echo "Generating files using build_runner..."
-          dart run build_runner build --delete-conflicting-outputs
-          
-          # Check if the command succeeded
-          if [ $? -ne 0 ]; then
-            echo "::error::Failed to generate files using build_runner."
-            echo "::error::Please check the build_runner output for errors."
-            exit 1
-          else
-            echo "Files generated successfully."
-          fi
-
-
-# Detect Asset File Changes
-      - name: Check Asset Files Changes
-        run: |
-          # Check if there are changes after generating asset files
-          git diff --exit-code lib/src/core/utils/gen/assets || (
-            echo "Error: Asset files are outdated. Run the generation command and commit the changes.";
-            exit 1;
-          )
-          
-          
-
-# Run Flutter Analyze
+        uses: ./.github/actions/generate-localization
+      - name: Generate Asset Files
+        uses: ./.github/actions/generate-assets
       - name: Run Flutter Analyze
         run: flutter analyze
+      - name: Fetch and Extract Files
+        uses: ./.github/actions/linux-extract-files
+      - name: Build application
+        run: flutter build linux --release
+      - name: Linux Archive Release
+        uses: ./.github/actions/linux-archive-release
 
 
-# Run tests
-      - name: Run tests
-        run: flutter test
+
+      - name: Create Linux Release
+        id: create_linux_release
+        uses: actions/create-release@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          tag_name: linux-release-${{ github.run_number }}
+          release_name: Linux Release ${{ github.run_number }}
+          body: |
+            Linux release from merged PR #${{ github.event.pull_request.number }}
+            ${{ github.event.pull_request.title }}
+          draft: false
+          prerelease: false
+
+      - name: Upload Linux Release Asset
+        uses: softprops/action-gh-release@v1
+        with:
+          tag_name: linux-build-release-${{ github.run_number }}
+          files: build/linux/x64/release/bundle/linux-build.zip
+
+
+#  build-and-release-windows:
+#    if: github.event.pull_request.merged == true
+#    runs-on: windows-latest
+#    strategy:
+#      matrix:
+#        arch: [amd64, 386]
+#    outputs:
+#      release_tag: windows-${{ matrix.arch }}-release-${{ github.run_number }}
+#      platform: Windows
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v4
+#
+#      - name: Setup Flutter
+#        uses: subosito/flutter-action@v2
+#        with:
+#          flutter-version: '3.27.3'
+#          channel: 'stable'
+#          cache: true
+#
+#      - name: Enable Windows desktop
+#        run: flutter config --enable-windows-desktop
+#
+#      - name: Get dependencies
+#        run: flutter pub get
+#
+#      - name: Fetch and Extract File
+#        shell: pwsh
+#        run: |
+#          New-Item -Path "$GITHUB_WORKSPACE/lib/src/core/native_resources/windows" -ItemType Directory -Force
+#          $assetsUrl = if ("${{ matrix.arch }}" -eq "amd64") { "${{ env.WINDOWS_AMD64_ASSETS_URL }}" } else { "${{ env.WINDOWS_386_ASSETS_URL }}" }
+#          Invoke-WebRequest -Uri $assetsUrl -OutFile "file.zip"
+#          Expand-Archive -Path "file.zip" -DestinationPath "$GITHUB_WORKSPACE/lib/src/core/native_resources/windows" -Force
+#
+#      - name: Build application
+#        run: |
+#          flutter doctor -v
+#          flutter build windows --release
+#          dir build\windows\x64\runner\Release
+#
+#      - name: Verify build directory
+#        run: |
+#          if (Test-Path "build\windows\x64\runner\Release") {
+#              echo "✓ Build directory exists"
+#              dir build\windows\x64\runner\Release
+#          } else {
+#              echo "× Build directory not found"
+#              exit 1
+#          }
+#
+#      - name: Archive Release
+#        shell: pwsh
+#        run: |
+#          cd build/windows/x64/runner/Release
+#          Copy-Item -Path "$GITHUB_WORKSPACE/lib/src/core/native_resources/windows/*" -Destination "." -Recurse -Force
+#          Compress-Archive -Path * -DestinationPath windows-${{ matrix.arch }}-build.zip -Force
+#
+#      - name: Create Windows Release
+#        id: create_windows_release
+#        uses: actions/create-release@v1
+#        env:
+#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#        with:
+#          tag_name: windows-${{ matrix.arch }}-release-${{ github.run_number }}
+#          release_name: Windows ${{ matrix.arch }} Release ${{ github.run_number }}
+#          body: |
+#            Windows ${{ matrix.arch }} release from merged PR #${{ github.event.pull_request.number }}
+#            ${{ github.event.pull_request.title }}
+#          draft: false
+#          prerelease: false
+#
+#      - name: Upload Windows Release Asset
+#        uses: softprops/action-gh-release@v1
+#        with:
+#          tag_name: windows-${{ matrix.arch }}-release-${{ github.run_number }}
+#          files: build/windows/x64/runner/Release/windows-${{ matrix.arch }}-build.zip
+#
+#  build-and-release-macos:
+#    if: github.event.pull_request.merged == true
+#    runs-on: macos-latest
+#    strategy:
+#      matrix:
+#        arch: [arm64, amd64]
+#    outputs:
+#      release_tag: macos-${{ matrix.arch }}-release-${{ github.run_number }}
+#      platform: macOS
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v4
+#
+#      - name: Setup Flutter
+#        uses: subosito/flutter-action@v2
+#        with:
+#          flutter-version: '3.27.3'
+#          channel: 'stable'
+#          cache: true
+#
+#      - name: Enable macOS desktop
+#        run: flutter config --enable-macos-desktop
+#
+#      - name: Get dependencies
+#        run: flutter pub get
+#
+#      - name: Fetch and Extract File
+#        run: |
+#          mkdir -p lib/src/core/native_resources/macos/
+#          assetsUrl=$(if [ "${{ matrix.arch }}" = "arm64" ]; then echo "${{ env.MACOS_ARM64_ASSETS_URL }}"; else echo "${{ env.MACOS_AMD64_ASSETS_URL }}"; fi)
+#          curl -L -o file.tar.gz $assetsUrl
+#          tar -xzf file.tar.gz --strip-components=1 -C lib/src/core/native_resources/macos/
+#
+#      - name: Build application
+#        run: |
+#          flutter doctor -v
+#          flutter build macos --release
+#          ls build/macos/Build/Products/Release
+#
+#      - name: Verify build directory
+#        run: |
+#          if [ -d "build/macos/Build/Products/Release" ]; then
+#            echo "✓ Build directory exists"
+#            ls -la build/macos/Build/Products/Release
+#          else
+#            echo "× Build directory not found"
+#            exit 1
+#          fi
+#
+#      - name: Archive Release
+#        run: |
+#          cd build/macos/Build/Products/Release
+#          cp -r $GITHUB_WORKSPACE/lib/src/core/native_resources/macos/* .
+#          zip -r macos-${{ matrix.arch }}-build.zip ./*
+#
+#      - name: Create macOS Release
+#        id: create_macos_release
+#        uses: actions/create-release@v1
+#        env:
+#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#        with:
+#          tag_name: macos-${{ matrix.arch }}-release-${{ github.run_number }}
+#          release_name: macOS ${{ matrix.arch }} Release ${{ github.run_number }}
+#          body: |
+#            macOS ${{ matrix.arch }} release from merged PR #${{ github.event.pull_request.number }}
+#            ${{ github.event.pull_request.title }}
+#          draft: false
+#          prerelease: false
+#
+#      - name: Upload macOS Release Asset
+#        uses: softprops/action-gh-release@v1
+#        with:
+#          tag_name: macos-${{ matrix.arch }}-release-${{ github.run_number }}
+#          files: build/macos/Build/Products/Release/macos-${{ matrix.arch }}-build.zip
+#
