Develop (#18)
* release: create release for v1.0.0

Changelog:
- Added new feature X
- Fixed bug Y

* release: create release for v1.0.0

Changelog:
- Added new feature X
- Fixed bug Y

* release: create release for v1.0.0

Changelog:
- Added new feature X
- Fixed bug Y

* release: create release for v1.0.0

Changelog:
- Added new feature X
- Fixed bug Y

* release: create release for v1.0.0

Changelog:
- Added new feature X
- Fixed bug Y

* release: create release for v1.0.0

Changelog:
- Added new feature X
- Fixed bug Y

* release: v1.0.0

Changelog:
- Added new feature X
- Fixed bug Y

* release: v1.0.0

Changelog:
- Added new feature X
- Fixed bug Y

* release: v1.0.0

release: v1.0.0
Changelog:
- Added new feature X
- Fixed bug Y

* release: v1.0.0

release: v1.0.0
Changelog:
- Added new feature X
- Fixed bug Y

* release: v1.0.0

release: v1.0.0
Changelog:
- Added new feature X
- Fixed bug Y

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -18,6 +18,8 @@ on:
     branches: [ "main" ]
 
 jobs:
+
+
   build-and-release-linux:
     if: github.event.pull_request.merged == true
     runs-on: ubuntu-latest
@@ -47,8 +49,75 @@ jobs:
       - name: Enable Linux desktop
         run: flutter config --enable-linux-desktop
 
-      - name: Get dependencies
+
+
+
+
+      - name: Install dependencies
         run: flutter pub get
+      - name: Run Dart Format Check (Efficient)
+        run: |
+          dart format . --set-exit-if-changed --output none || (
+            echo "Code formatting issues detected. Run 'dart format .' and commit the changes.";
+            exit 1;
+          )
+      - name: Generate Localization Files
+        id: gen_l10n
+        run: |
+          # Run the command to generate localization files and capture the output
+          output=$(flutter gen-l10n)
+          echo "$output"
+          
+          # Check if there are untranslated messages in the output
+          if echo "$output" | grep -q "untranslated message"; then
+            echo "::error file=lib/l10n/l10n.yaml::Error: Untranslated messages detected in your localization files."
+            echo "::error::There are untranslated messages in the following languages:"
+            echo "$output" | grep "untranslated message"
+            echo "::error::Please ensure that all translations are provided in the respective .arb files."
+            exit 1
+          fi
+      - name: Check Localization Files
+        run: |
+          git diff --exit-code lib/l10n/ || (
+            echo "Localization files are outdated. Run 'flutter gen-l10n' and commit changes.";
+            exit 1;
+          )
+      - name: Check if translations_utils.dart has changes
+        run: |
+          git diff --exit-code lib/src/core/utils/gen/localization/translations_utils.dart || (
+            echo "Error: Changes detected in translations_utils.dart. Please run the necessary custom translation utilities and commit changes.";
+            exit 1;
+          )
+      - name: Generate Assets Files
+        run: |
+          # Command to rebuild asset files
+          dart run build_runner build --delete-conflicting-outputs || (
+            echo "Error: Failed to generate asset files.";
+            exit 1;
+          )
+      - name: Check Asset Files Changes
+        run: |
+          # Check if there are changes after generating asset files
+          git diff --exit-code lib/src/core/utils/gen/assets || (
+            echo "Error: Asset files are outdated. Run the generation command and commit the changes.";
+            exit 1;
+          )
+      - name: Run Flutter Analyze
+        run: flutter analyze
+      - name: Run Dart Format and Check Localization Files Changes
+        run: |
+          # Run dart format without failing the step
+          dart format . || echo "dart format completed with warnings, but continuing pipeline."
+          
+          # Check if there are changes in the localization files after generation
+          git diff --exit-code lib/src/core/utils/gen/localization || (
+            echo "Error: Localization files are outdated. Run the generation command and commit the changes.";
+            exit 1;
+          )
+      - name: Run tests
+        run: flutter test
+
+
 
       - name: Fetch and Extract File
         run: |
@@ -84,6 +153,8 @@ jobs:
         with:
           tag_name: linux-release-${{ github.run_number }}
           files: build/linux/x64/release/bundle/linux-build.zip
+      - name: Get dependencies
+        run: flutter pub get
 
   build-and-release-windows:
     if: github.event.pull_request.merged == true
