update: v1.0.1

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2,7 +2,7 @@ name: Linting & Tests Validation
 on:
   pull_request:
     branches:
-      - develop
+      - main
 jobs:
   lint_and_test:
     runs-on: ubuntu-latest
@@ -13,29 +13,21 @@ jobs:
         uses: subosito/flutter-action@v2
         with:
           flutter-version: '3.27.3'
-
-
-# Install dependencies
       - name: Install dependencies
         run: flutter pub get
-
-
-# Detect Dart Formatting Issues
       - name: Run Dart Format Check (Efficient)
         run: |
           dart format . --set-exit-if-changed --output none || (
             echo "Code formatting issues detected. Run 'dart format .' and commit the changes.";
             exit 1;
           )
-          
-# Generate Localization Files
       - name: Generate Localization Files
         id: gen_l10n
         run: |
           # Run the command to generate localization files and capture the output
           output=$(flutter gen-l10n)
           echo "$output"
-
+          
           # Check if there are untranslated messages in the output
           if echo "$output" | grep -q "untranslated message"; then
             echo "::error file=lib/l10n/l10n.yaml::Error: Untranslated messages detected in your localization files."
@@ -44,48 +36,25 @@ jobs:
             echo "::error::Please ensure that all translations are provided in the respective .arb files."
             exit 1
           fi
-
-# Detect Localization Files Changes
-      - name: Validate Generated Localization Files
+      - name: Check Localization Files
         run: |
-          # Check if localization files have changes
-          if git diff --exit-code lib/l10n/; then
-            echo "Localization files are up to date."
-          else
-            echo "::error file=lib/l10n/::Error: Localization files are outdated."
-            echo "::error::Please run 'flutter gen-l10n' and commit the changes."
-            exit 1
-          fi
-
-          # Check if translations_utils.dart has changes
-          if git diff --exit-code lib/src/core/utils/gen/localization/translations_utils.dart; then
-            echo "translations_utils.dart is up to date."
-          else
-            echo "::error file=lib/src/core/utils/gen/localization/translations_utils.dart::Error: Changes detected in translations_utils.dart."
-            echo "::error::Please run the necessary custom translation utilities and commit changes."
-            exit 1
-          fi
-
-
-
-# Generate Files Using build_runner
-      - name: Generate Files Using build_runner
+          git diff --exit-code lib/l10n/ || (
+            echo "Localization files are outdated. Run 'flutter gen-l10n' and commit changes.";
+            exit 1;
+          )
+      - name: Check if translations_utils.dart has changes
         run: |
-          # Run build_runner to generate files
-          echo "Generating files using build_runner..."
-          dart run build_runner build --delete-conflicting-outputs
-          
-          # Check if the command succeeded
-          if [ $? -ne 0 ]; then
-            echo "::error::Failed to generate files using build_runner."
-            echo "::error::Please check the build_runner output for errors."
-            exit 1
-          else
-            echo "Files generated successfully."
-          fi
-
-
-# Detect Asset File Changes
+          git diff --exit-code lib/src/core/utils/gen/localization/translations_utils.dart || (
+            echo "Error: Changes detected in translations_utils.dart. Please run the necessary custom translation utilities and commit changes.";
+            exit 1;
+          )
+      - name: Generate Assets Files
+        run: |
+          # Command to rebuild asset files
+          dart run build_runner build --delete-conflicting-outputs || (
+            echo "Error: Failed to generate asset files.";
+            exit 1;
+          )
       - name: Check Asset Files Changes
         run: |
           # Check if there are changes after generating asset files
@@ -93,14 +62,26 @@ jobs:
             echo "Error: Asset files are outdated. Run the generation command and commit the changes.";
             exit 1;
           )
-          
-          
-
-# Run Flutter Analyze
       - name: Run Flutter Analyze
         run: flutter analyze
-
-
-# Run tests
+      - name: Run Dart Format and Check Localization Files Changes
+        run: |
+          # Run dart format without failing the step
+          dart format . || echo "dart format completed with warnings, but continuing pipeline."
+          
+          # Check if there are changes in the localization files after generation
+          git diff --exit-code lib/src/core/utils/gen/localization || (
+            echo "Error: Localization files are outdated. Run the generation command and commit the changes.";
+            exit 1;
+          )
       - name: Run tests
         run: flutter test
+  merge_check:
+    runs-on: ubuntu-latest
+    needs: lint_and_test
+    if: ${{ success() }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+      - name: Merge Pull Request
+        run: echo "Linting and tests passed successfully.Merge request is ready for merge"
